### PR TITLE
Some tests.

### PR DESCRIPTION
**Pull request by JamesTFarrington**
This is still a work in progress. Currently test_runner_cleanup passes. test_runner_is_busy fails if test_runner_cleanup is present, but passes when it is absent.

I've made runner.cleanup it's own callback, which is easier to test, and should work better.

### CODE REVIEW

**Comment by jMyles** [comment]
Can you open this against tiempo:2.0 instead of jMyles:now ?

**Comment by JamesTFarrington** [comment]
On hangarunderground or jmyles?

**Comment by jMyles** [comment]
Righto!  I meant hangarunderground:2.0.

**Comment by jMyles** [comment]
Subsumed by https://github.com/jMyles/tiempo/pull/3.

**Pull request closed without merging**
